#!/usr/bin/env bash
# Keep a tracked copy of .claude/CLAUDE.md, which git cannot track in place.
#
# WHY A MIRROR AND NOT A NEGATION. `.claude/` contains a clone of
# kepano/obsidian-skills, so `.claude/.git` is a repository boundary. Git will
# not descend past one: `git add .claude/CLAUDE.md` exits 0 and stages nothing,
# with no warning. The .gitignore negation was necessary and not sufficient, and
# it took reading `git show --stat` to notice that a commit claiming to track
# the file contained only the .gitignore change.
#
# A symlink would also work and was rejected: after a fresh clone the symlink
# itself lives inside the ignored directory, so it would not exist, and
# CLAUDE.md would silently be missing on a new machine. A copy is recoverable
# by hand from a filename that says what it is.
#
# THE LIVE FILE REMAINS `.claude/CLAUDE.md`. This is a backup and a history, not
# a second source: edit the live one, and this follows on the next Stop hook.
# The direction matters, so the mirror is one-way and the copy says so at the
# top of itself.
set -euo pipefail

VAULT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$VAULT/.claude/CLAUDE.md"
DST="$VAULT/analysis/vault-instructions.md"

[ -f "$SRC" ] || exit 0

HEADER="<!-- MIRROR — DO NOT EDIT.
     The live file is .claude/CLAUDE.md. Git cannot track it: .claude/ holds a
     clone of kepano/obsidian-skills, and git will not descend past a nested
     .git. This copy exists so the instructions that govern this vault have a
     history and a remote copy. Regenerated by analysis/scripts/mirror_claude_md.sh
     on the Stop hook; edit the live file and this follows.
     Restore with:  cp analysis/vault-instructions.md .claude/CLAUDE.md
-->

"

want="$HEADER$(cat "$SRC")"
if [ -f "$DST" ] && [ "$want" = "$(cat "$DST")" ]; then
  exit 0                      # unchanged; do not churn the working tree
fi
printf '%s\n' "$want" > "$DST"
[ "${1:-}" = "--quiet" ] || echo "mirrored CLAUDE.md -> ${DST#"$VAULT"/}"
