#!/usr/bin/env bash
# What has not been reviewed, computed from git state, for whoever is asking.
#
# WHY THIS EXISTS. CLAUDE.md has said "start the review yourself, do not ask
# permission" for weeks. On 2026-09-20 an entire evening of new tooling - a CI
# suite, an orb widget, two third-opinion scripts, a bridge change - was written
# and committed without a single review, until TC noticed and asked. A rule that
# depends on an agent remembering it is the weakest form of that rule. This
# turns it into something the tooling says out loud, every turn.
#
# IT SERVES TWO READERS, WHICH IS WHY IT WRITES A FILE AND NOT JUST A LINE.
# Claude Code gets the one-line summary through the Stop hook. Claude Science
# has no hooks and cannot run either CLI - it reads the vault. So the same
# computation lands in analysis/review-status.md, which is tracked, so anything
# working in this vault can see what is outstanding and ask for it through the
# bridge.
#
#   bash analysis/scripts/review_status.sh            # write the file, print a summary
#   bash analysis/scripts/review_status.sh --quiet    # write the file only
set -euo pipefail

VAULT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$VAULT"
TO_STATE=".claude/third-opinion"
OUT="analysis/review-status.md"

# Codex's backlog is already computed from git state by its own script; asking
# it is better than reimplementing `classify` here and letting the two drift.
codex_pending="$(bash analysis/scripts/codex_review.sh pending 2>/dev/null || true)"
codex_n="$(printf '%s' "$codex_pending" | grep -c . || true)"

# The third opinion is for DOCUMENTS AT A CHECKPOINT, not for every file that
# changed. Its value is a cold read of work Claude and Codex have converged on,
# so scripts are deliberately out of scope here - running it on every code edit
# would turn the third reviewer into a third voice, which is the thing it was
# introduced not to be.
third_pending=""
while IFS= read -r p; do
  [ -n "$p" ] || continue
  blob="$(git hash-object "$p" 2>/dev/null || echo MISSING)"
  seen="$(awk -F'\t' -v q="$p" '$1 == q { h = $2 } END { print h }' \
          "$TO_STATE/reviewed.tsv" 2>/dev/null || true)"
  [ "$blob" = "$seen" ] && continue
  third_pending="${third_pending}${p}"$'\n'
done < <(git ls-files 'proposals/*.md' 'experiments/*/reports/*.md' 'fellowships/*/drafts/*.md' 2>/dev/null)
third_n="$(printf '%s' "$third_pending" | grep -c . || true)"

{
  echo "---"
  echo "type: reference"
  echo "tags: [review, codex, third-opinion]"
  echo "updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "---"
  echo
  echo "# Review status"
  echo
  echo "*Generated by \`analysis/scripts/review_status.sh\` from git state — a file re-enters a"
  echo "backlog whenever its contents change, so this cannot go stale while the work moves.*"
  echo
  echo "**Codex: $codex_n file(s) pending.** Second reviewer for code, reports and proposals."
  if [ "$codex_n" -gt 0 ]; then
    echo
    printf '%s\n' "$codex_pending" | sed 's/^/    /'
  fi
  echo
  echo "**Third opinion: $third_n document(s) never seen at their current text.** A blinded cold"
  echo "read, for documents at a checkpoint — not for every edit."
  if [ "$third_n" -gt 0 ]; then
    echo
    printf '%s' "$third_pending" | sed 's/^/    /'
  fi
  echo
  if [ -f .claude/tribunal/latest.json ]; then
    _lt="$(sed -n 's/.*"finished_at": "\([^"]*\)".*/\1/p' .claude/tribunal/latest.json)"
    _ld="$(sed -n 's/.*"dir": "\([^"]*\)".*/\1/p' .claude/tribunal/latest.json)"
    _lf="$(sed -n 's/.*"files": "\([^"]*\)".*/\1/p' .claude/tribunal/latest.json)"
    echo "**Last sitting:** \`$_lf\` at $_lt — verdicts in \`$_ld\`."
    echo "A run that finished while nobody was watching still happened; read it before assuming it did not."
    echo
  fi
  echo "## \"Consult the tribunal\""
  echo
  echo "Both judges on one document, in order — Codex on the evidence, then the blinded cold read."
  echo "TC can say it to either agent, or press the orb's tribunal button."
  echo
  echo "## Asking for one"
  echo
  echo "**Claude Code** runs them directly:"
  echo '```bash'
  echo "bash analysis/scripts/codex_review.sh begin      # then: run <id>"
  echo "bash analysis/scripts/third_opinion.sh <paths>"
  echo '```'
  echo
  echo "**Claude Science** cannot — Codex will not nest its sandbox inside the cell, and that"
  echo "environment's TLS interception blocks the API route. It asks through the bridge instead,"
  echo "by writing \`analysis/codex_bridge/inbox/<ID>.md\`:"
  echo
  echo '```markdown'
  echo "<!-- reviewer: gemini -->"
  echo "<!-- files: proposals/TC_004_TH3_brief_glycan-state-exhaustion.md -->"
  echo "Cold read before this goes to the advisor."
  echo '```'
  echo
  echo "\`reviewer:\` defaults to \`codex\`. With \`files:\` a Gemini request is blinded — the bundle"
  echo "refuses to include any review or bridge reply. Without it, the brief is sent as written and"
  echo "the reply's \`.meta.json\` records \`\"blinded\":\"no\"\`, because a third opinion that read the"
  echo "second opinion is a different thing wearing the same name."
  echo
  echo "**Neither reviewer's findings are ever applied automatically.** They are verified, argued"
  echo "with, and brought to TC to decide."
} > "$OUT"

if [ "${1:-}" != "--quiet" ]; then
  if [ "$codex_n" -gt 0 ] || [ "$third_n" -gt 0 ]; then
    echo "Review pending: ${codex_n} file(s) for Codex, ${third_n} document(s) for a third opinion. Start them; do not ask."
  fi
fi
